name: cmpt419_project_pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23
  - pandas
  - matplotlib
  - ipykernel
  - jupyterlab
  - jupyter
  - ipywidgets
  - scikit-learn
  - tqdm
  - pydicom
  - seaborn
  - scipy
  - h5py
  - pip
  - pip:
      - torch==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - torchaudio==2.6.0+cu118
      - torchinfo
      - flask
      - flask-cors
      - --extra-index-url https://download.pytorch.org/whl/cu118
